server:
    port: ${PORT}
app:
  api-items:
    endpoint: ${ENDPOINT_API_ITEMS}
management:
   endpoints:
      web:
         exposure:
            include: prometheus,health,info,metric   
logging:
  level:
    root: INFO    
spring:
  jackson:
      default-property-inclusion: non_null             

