apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: ${project.artifactId}
  name: ${project.artifactId}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${project.artifactId}
  maxReplicas: ${max.replicas}
  minReplicas: ${min.replicas}
  targetCPUUtilizationPercentage: ${target.cpu}